// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace EToolsSecurity.Entities
{
    /// <summary>
    /// Class Employee.
    /// </summary>
    internal partial class Employee
    {
        /// <summary>
        /// Gets or sets the employee identifier.
        /// </summary>
        /// <value>The employee identifier.</value>
        [Key]
        public int EmployeeID { get; set; }
        /// <summary>
        /// Gets or sets the first name.
        /// </summary>
        /// <value>The first name.</value>
        [Required]
        [StringLength(25)]
        public string FirstName { get; set; }
        /// <summary>
        /// Gets or sets the last name.
        /// </summary>
        /// <value>The last name.</value>
        [Required]
        [StringLength(25)]
        public string LastName { get; set; }
        /// <summary>
        /// Gets or sets the date hired.
        /// </summary>
        /// <value>The date hired.</value>
        [Column(TypeName = "datetime")]
        public DateTime DateHired { get; set; }
        /// <summary>
        /// Gets or sets the date released.
        /// </summary>
        /// <value>The date released.</value>
        [Column(TypeName = "datetime")]
        public DateTime? DateReleased { get; set; }
        /// <summary>
        /// Gets or sets the position identifier.
        /// </summary>
        /// <value>The position identifier.</value>
        public int PositionID { get; set; }
        /// <summary>
        /// Gets or sets the login identifier.
        /// </summary>
        /// <value>The login identifier.</value>
        [StringLength(30)]
        public string LoginID { get; set; }
        /// <summary>
        /// Gets or sets the address.
        /// </summary>
        /// <value>The address.</value>
        [Required]
        [StringLength(75)]
        public string Address { get; set; }
        /// <summary>
        /// Gets or sets the city.
        /// </summary>
        /// <value>The city.</value>
        [Required]
        [StringLength(30)]
        public string City { get; set; }
        /// <summary>
        /// Gets or sets the contact phone.
        /// </summary>
        /// <value>The contact phone.</value>
        [Required]
        [StringLength(12)]
        public string ContactPhone { get; set; }
        /// <summary>
        /// Gets or sets the postal code.
        /// </summary>
        /// <value>The postal code.</value>
        [Required]
        [StringLength(6)]
        public string PostalCode { get; set; }
    }
}