// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EToolsSecurity.Entities;

namespace EToolsSecurity.DAL
{
    /// <summary>
    /// Class eTools2021Context.
    /// Implements the <see cref="DbContext" />
    /// </summary>
    /// <seealso cref="DbContext" />
    internal partial class eTools2021Context : DbContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="eTools2021Context"/> class.
        /// </summary>
        /// <remarks>See <see href="https://aka.ms/efcore-docs-dbcontext">DbContext lifetime, configuration, and initialization</see>
        /// for more information and examples.</remarks>
        public eTools2021Context()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="eTools2021Context"/> class.
        /// </summary>
        /// <param name="options">The options.</param>
        public eTools2021Context(DbContextOptions<eTools2021Context> options)
            : base(options)
        {
        }

        /// <summary>
        /// Gets or sets the employees.
        /// </summary>
        /// <value>The employees.</value>
        public virtual DbSet<Employee> Employees { get; set; }

        /// <summary>
        /// Override this method to further configure the model that was discovered by convention from the entity types
        /// exposed in <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on your derived context. The resulting model may be cached
        /// and re-used for subsequent instances of your derived context.
        /// </summary>
        /// <param name="modelBuilder">The builder being used to construct the model for this context. Databases (and other extensions) typically
        /// define extension methods on this object that allow you to configure aspects of the model that are specific
        /// to a given database.</param>
        /// <remarks><para>
        /// If a model is explicitly set on the options for this context (via <see cref="M:Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.UseModel(Microsoft.EntityFrameworkCore.Metadata.IModel)" />)
        /// then this method will not be run. However, it will still run when creating a compiled model.
        /// </para>
        /// <para>
        /// See <see href="https://aka.ms/efcore-docs-modeling">Modeling entity types and relationships</see> for more information and
        /// examples.
        /// </para></remarks>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>(entity =>
            {
                entity.Property(e => e.ContactPhone).IsFixedLength();

                entity.Property(e => e.PostalCode).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        /// <summary>
        /// Called when [model creating partial].
        /// </summary>
        /// <param name="modelBuilder">The model builder.</param>
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}