// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rentals.Entities
{
    internal partial class Customer
    {
        public Customer()
        {
            Rentals = new HashSet<Rental>();
        }

        [Key]
        public int CustomerID { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(75)]
        public string Address { get; set; }
        [Required]
        [StringLength(30)]
        public string City { get; set; }
        [Required]
        [StringLength(2)]
        public string ProvinceID { get; set; }
        [Required]
        [StringLength(6)]
        public string PostalCode { get; set; }
        [Required]
        [StringLength(12)]
        public string ContactPhone { get; set; }
        [StringLength(50)]
        public string EmailAddress { get; set; }
        public bool AcceptableStatus { get; set; }

        [InverseProperty("Customer")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}