// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rentals.Entities
{
    internal partial class RentalDetail
    {
        [Key]
        public int RentalDetailID { get; set; }
        public int RentalID { get; set; }
        public int RentalEquipmentID { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal RentalDays { get; set; }
        [Column(TypeName = "money")]
        public decimal RentalRate { get; set; }
        [Required]
        [StringLength(100)]
        public string OutCondition { get; set; }
        [Required]
        [StringLength(100)]
        public string InCondition { get; set; }
        [Column(TypeName = "money")]
        public decimal DamageRepairCost { get; set; }
        [StringLength(500)]
        public string Comments { get; set; }

        [ForeignKey("RentalID")]
        [InverseProperty("RentalDetails")]
        public virtual Rental Rental { get; set; }
        [ForeignKey("RentalEquipmentID")]
        [InverseProperty("RentalDetails")]
        public virtual RentalEquipment RentalEquipment { get; set; }
    }
}