// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rentals.Entities
{
    internal partial class Rental
    {
        public Rental()
        {
            RentalDetails = new HashSet<RentalDetail>();
        }

        [Key]
        public int RentalID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public int? CouponID { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal SubTotal { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal TaxAmount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RentalDateOut { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RentalDateIn { get; set; }
        [Required]
        [StringLength(1)]
        public string PaymentType { get; set; }

        [ForeignKey("CouponID")]
        [InverseProperty("Rentals")]
        public virtual Coupon Coupon { get; set; }
        [ForeignKey("CustomerID")]
        [InverseProperty("Rentals")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("EmployeeID")]
        [InverseProperty("Rentals")]
        public virtual Employee Employee { get; set; }
        [InverseProperty("Rental")]
        public virtual ICollection<RentalDetail> RentalDetails { get; set; }
    }
}